language: generic
env:
  - PPA=yes
  - PPA=no

install:
  - if [ x"$PPA" == "xyes" ] ; then sudo add-apt-repository ppa:pi-rho/dev -y; fi
  - sudo apt-get update -q
  - sudo apt-get install vim-nox

before_script:
  - git clone https://github.com/vim-jp/vital.vim /tmp/vital.vim
  - git clone https://github.com/thinca/vim-themis --branch v1.4 --single-branch --depth 1 /tmp/vim-themis
  - vim --cmd version --cmd quit

script:
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - /tmp/vim-themis/bin/themis test/themis --runtimepath /tmp/vital.vim --reporter spec
